### ISSUE TITLE
Slimming of conda containers raises 'ModuleNotFoundError'

### ISSUE THREAD

**Issue by alexiswl** [docker-slim/docker-slim#130] opened 2020-02-14 00:32 UTC
Hello, I'm trying to 'slim' my pandas image., alexiswl/alpine_pandas:latest.

To show it works as is, I create the following python script:
```
% cat pandas_test.py 
#!/usr/bin/env python3

import pandas as pd
import sys

print(pd.DataFrame({"A": [1, 2, 3]}))
sys.exit()
```

And run it through docker
```
% docker run -v $PWD:/mnt/scripts alexiswl/alpine_pandas:latest /mnt/scripts/pandas_test.py
   A
0  1
1  2
2  3
```

I then slim the image with docker-slim.

```
docker run -v /var/run/docker.sock:/var/run/docker.sock dslim/docker-slim --in-container build --http-probe=false alexiswl/alpine_pandas:latest
```

I then rerun the test script with the new slim image:
```
% docker run -i -t -v $PWD:/mnt/scripts alexiswl/alpine_pandas.slim:latest /mnt/scripts/pandas_test.py
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Traceback (most recent call last):
  File "/mnt/scripts/pandas_test.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

Do I need to set `PYTHONHOME` to something? I've tried both `/opt/conda` and `/opt/conda/bin`, neither of which Ive had any success with. The latter changes the error to `ModuleNotFoundError: No module named 'encodings'`.

**Comment by brainstorm** [comment] 2020-02-14 00:39
This is very closely related to https://github.com/docker-slim/docker-slim/issues/117, I hope you can reproduce it now much more comfortably, @kcq.

The other container (UMCCRISE) had too big reference files to reproduce, this one is more manageable, sorry for the delay ;)

**Comment by kcq** [comment] 2020-02-25 16:41
@alexiswl is this the Dockerfile for your image? https://github.com/alexiswl/alpine-images/blob/master/python-pandas/1.0.1/Dockerfile

**Comment by kcq** [comment] 2020-02-25 16:57
@alexiswl minifying a base image requires a bit of extra work because docker-slim doesn't know the intended use for the container image. When you minify an image with a specific application in it docker-slim observes its behavior and discovers its dependencies. In this case, the 'pandas' package is missing because there isn't an application that loads it. There's a few options to try... There's a set of `--include-*` parameters (e.g., `--include-path`) that tell `docker-slim` to include specific artifacts from your original image. Another thing to try is adding a dummy app (like `pandas_test.py` you shared here) that uses the python packages you care about.

There's a number of enhancements planned to make it easier to minify base images (including an ability to use package names when you specify what artifacts you want to keep from the original image).

**Comment by kcq** [comment] 2020-02-25 16:57
@alexiswl minifying a base image requires a bit of extra work because docker-slim doesn't know the intended use for the container image. When you minify an image with a specific application in it docker-slim observes its behavior and discovers its dependencies. In this case, the 'pandas' package is missing because there isn't an application that loads it. There's a few options to try... There's a set of `--include-*` parameters (e.g., `--include-path`) that tell `docker-slim` to include specific artifacts from your original image. Another thing to try is adding a dummy app (like `pandas_test.py` you shared here) that uses the python packages you care about.

There's a number of enhancements planned to make it easier to minify base images (including an ability to use package names when you specify what artifacts you want to keep from the original image).

**Comment by alexiswl** [comment] 2020-02-25 23:15
> @alexiswl is this the Dockerfile for your image? https://github.com/alexiswl/alpine-images/blob/master/python-pandas/1.0.1/Dockerfile

Yes this the Dockerfile.

**Comment by alexiswl** [comment] 2020-02-25 23:19
> @alexiswl minifying a base image requires a bit of extra work because docker-slim doesn't know the intended use for the container image. When you minify an image with a specific application in it docker-slim observes its behavior and discovers its dependencies. In this case, the 'pandas' package is missing because there isn't an application that loads it. There's a few options to try... There's a set of `--include-*` parameters (e.g., `--include-path`) that tell `docker-slim` to include specific artifacts from your original image. Another thing to try is adding a dummy app (like `pandas_test.py` you shared here) that uses the python packages you care about.
> 
> There's a number of enhancements planned to make it easier to minify base images (including an ability to use package names when you specify what artifacts you want to keep from the original image).

Thank you does the `--include` or `--include-path` mean that if I use `--include /opt/conda` it will keep everything inside that?

If I add in pandas_test into the image, how can I tell docker-slim to look at the app without setting it as the entrypoint, or is this where the `--include` parameters come in handy?

**Comment by alexiswl** [comment] 2020-02-26 01:34
I had a try with the --include-path parameters.

```
docker run -v /var/run/docker.sock:/var/run/docker.sock dslim/docker-slim \
  --in-container build --http-probe=false \
  --include-path=/opt/conda/lib/python3.7/site-packages/pandas/ \
  --include-path /opt/conda/lib/python3.7/site-packages/numpy/ \
  --include-path /opt/conda/lib/python3.7/site-packages/pytz/ \
  --include-path /opt/conda/lib/python3.7/site-packages/dateutil/  \
  --exclude-path /opt/conda/lib/python3.7/site-packages/ \
  --include-path /opt/conda/lib/python3.7/ \
alexiswl/alpine_pandas:latest
```

This works but generates an image that's 211 Mb, which is of a similar order to the original image (260 Mb). It would also seem that the `--exclude-path` used here intended to remove all the other unnecessary packages is overwritten by the following `--include-path` (Deduced by the fact that the slim image size is the same with and without the `--exclude-path` parameter).

**Comment by kcq** [comment] 2020-02-26 15:57
@alexiswl Thank you for the update! Are 'pandas', 'numpy', 'pytz' and 'dateutil' the python packages you care about? What did you want to accomplish with the `--exclude-path` parameter? Is it how you wanted to indicate that you don't want any python packages except 'pandas', 'numpy', 'pytz' and 'dateutil'?

**Comment by kcq** [comment] 2020-02-26 16:02
@alexiswl Yes, `--include-path` means everything inside that directory will be included. This param will need to be enhanced to allow filtering because including everything might not be ideal.

**Comment by kcq** [comment] 2020-02-26 16:09
@alexiswl If you add `pandas_test.py` to your image you can tell `docker-slim` to use it as a temporary entrypoint when it's doing its analysis using the `--entrypoint` parameter (you don't need to change the ENTRYPOINT instruction in your Dockerfile). `docker-slim` will not persist this temporary entrypoint in the minified image. If you do want to replace the entrypoint in the minified image you'd use the `--new-entrypoint` parameter.

**Comment by alexiswl** [comment] 2020-02-26 23:34
> @alexiswl Thank you for the update! Are 'pandas', 'numpy', 'pytz' and 'dateutil' the python packages you care about? What did you want to accomplish with the `--exclude-path` parameter? Is it how you wanted to indicate that you don't want any python packages except 'pandas', 'numpy', 'pytz' and 'dateutil'?

Precisely, by a process of trial and error, these were the essentials modules inside the site-packages directory. However there were a few libraries in the top directory that were still needed which is why I had the final include-path there. 

> @alexiswl If you add `pandas_test.py` to your image you can tell `docker-slim` to use it as a temporary entrypoint when it's doing its analysis using the `--entrypoint` parameter (you don't need to change the ENTRYPOINT instruction in your Dockerfile). `docker-slim` will not persist this temporary entrypoint in the minified image. If you do want to replace the entrypoint in the minified image you'd use the `--new-entrypoint` parameter.

This worked, thank you so much!!
I used the following code to build the container:
```
docker run -v /var/run/docker.sock:/var/run/docker.sock dslim/docker-slim \
  --in-container build --http-probe=false \
  --mount $PWD:/mnt/scripts \
  --entrypoint /mnt/scripts/pandas_test.py \
  alexiswl/alpine_pandas:latest
```

This resulted in an image size of `117 Mb`. And then this is now my output!
```
$ docker run -v $PWD:/mnt/scripts alexiswl/alpine_pandas.slim:latest /mnt/scripts/pandas_test.py
   A
0  1
1  2
2  3
```

**Closed** 2020-02-27 21:38 UTC
