### ISSUE TITLE
Doesn't build on armhf

### ISSUE THREAD

**Issue by sokoow** [docker-slim/docker-slim#6] opened 2016-02-06 17:57 UTC
I'm getting a following when trying to build on armhf:

```
go build ./apps/docker-slim
# github.com/cloudimmunity/system
../system/system_linux.go:24: cannot use unameInfo.Sysname (type [65]uint8) as type [65]int8 in argument to nativeCharsToString
../system/system_linux.go:25: cannot use unameInfo.Nodename (type [65]uint8) as type [65]int8 in argument to nativeCharsToString
../system/system_linux.go:26: cannot use unameInfo.Release (type [65]uint8) as type [65]int8 in argument to nativeCharsToString
../system/system_linux.go:27: cannot use unameInfo.Version (type [65]uint8) as type [65]int8 in argument to nativeCharsToString
../system/system_linux.go:28: cannot use unameInfo.Machine (type [65]uint8) as type [65]int8 in argument to nativeCharsToString
../system/system_linux.go:29: cannot use unameInfo.Domainname (type [65]uint8) as type [65]int8 in argument to nativeCharsToString
```

**Comment by kcq** [comment] 2016-02-06 18:06
Sorry about that! And thank you for trying to build it on a new platform! Do you have a netbook? Can you share a bit more about your environment?

**Comment by sokoow** [comment] 2016-02-06 18:08
Sure,

I have armhf all over the place : Chromebook 2 arm and odroid-U3 platforms, all running ubuntu 15.10 and go 1.5.1. Can't beat 9 hours of battery on chromebook :D

**Comment by kcq** [comment] 2016-02-07 22:18
This is due to architecture differences... These tickets (in Go and Docker) provide a good overview: https://github.com/golang/go/issues/13318 , https://github.com/docker/docker/pull/18064 Doing the same thing Docker did should fix it :)

The syscall/seccomp functionality needs enhancements to support ARM architectures... That needs to be done in the "system" library (which covers only ArchName386 and ArchNameAmd64 at this point in time).

**Comment by kcq** [comment] 2016-02-07 22:57
This should be fixed, but there are a couple of other arm build errors that need to be addressed too:

docker-slim/sensor/monitors/fanotify/monitor.go:30: nd.Mark undefined (type *fanotify.NotifyFD has no field or method Mark)

docker-slim/sensor/monitors/ptrace/monitor.go:91: regs.Orig_rax undefined (type syscall.PtraceRegs has no field or method Orig_rax)

docker-slim/sensor/monitors/ptrace/monitor.go:99: regs.Rax undefined (type syscall.PtraceRegs has no field or method Rax)

**Comment by vanloswang** [comment] 2016-06-25 16:14
@kcq @sokoow  
docker-slim/sensor/monitors/fanotify/monitor.go:30: nd.Mark undefined (type *fanotify.NotifyFD has no field or method Mark)
caused by missing bitbucket.org/madmo/fanotify/fanotify_arm.go or bitbucket.org/madmo/fanotify/fanotify_arm64.go

docker-slim/sensor/monitors/ptrace/monitor.go:91: regs.Orig_rax undefined (type syscall.PtraceRegs has no field or method Orig_rax)

docker-slim/sensor/monitors/ptrace/monitor.go:99: regs.Rax undefined (type syscall.PtraceRegs has no field or method Rax)

I did not  found a solution now.

**Comment by kcq** [comment] 2017-08-10 13:36
Moving ARM support to the Wishlist. Ping me if you want to help :-)

**Closed by kcq** 2017-08-10 13:36 UTC
Labels: enhancement, help wanted

**Comment by IstenesImre** [comment] 2019-02-05 09:20
Ping? :)

**Comment by jishminor** [comment] 2019-04-12 21:20
I have built and tested out dockerslim on armhf, but had a make a few changes specific to the arm architecture in the ptrace module, as well as some of the packages in the vendor directory. Do you have any regression tests suites to run to ensure that nothing has broken for the x86 builds?

**Comment by kcq** [comment] 2019-04-13 00:32
Thank you for working on this Josh! This is great! There's no automated regression test suite at this point in time, but there's a set of sample applications you can minify and confirm everything is still working. The examples are now in a separate repo ( https://github.com/docker-slim/examples ). Checking if the minified `ruby_ubuntu`, `ruby_rails_standard`, `ruby_alpine`, `python_alpine` and `python_centos7_py27_standard` apps work is a good way to confirm. I'll be happy to help with the process.
